spring:
  h2:
    console:
      path: /console
  datasource:
    url: jdbc:h2:mem:taco-app
  application:
    name: Taco-API

server:
  port: 8443
  ssl:
    key-store: /Users/andreybevilacqua/Documents/java/workspace/taco-cloud/taco/mykeys.jks
    key-store-password: 123456
    key-password: 123456

logging:
  path: /Users/andreybevilacqua/Downloads
  file: taco.log

taco:
  orders:
    pageSize: 10
  integration:
    folder: /Users/andreybevilacqua/Downloads