spring:
  h2:
    console:
      path: /console
  datasource:
    url: jdbc:h2:mem:taco-app
  application:
    name: Taco-API
  cloud:
    config:
      uri: http://localhost:8888

# By default, when you add Eureka client as dependency, it will try to find Eureka server in localhost:8761.
# For production, you need to specify the location of the Eureka server.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080
#  ssl:
#    key-store: /Users/andreybevilacqua/Documents/java/workspace/taco-cloud/taco/mykeys.jks
#    key-store-password: 123456
#    key-password: 123456

logging:
  path: /Users/andreybevilacqua/Downloads
  file: taco.log

taco:
  orders:
    pageSize: 10
  integration:
    folder: /Users/andreybevilacqua/Downloads

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  contact:
    email: my-email@email.com
    phone: 123-456-7890
