server:
  port: 8080
spring:
  artemis: #ActiveMQ Artemis
    host: tcp://localhost:61616
    user: admin
    password: admin
    mode: native
  jms:
    template:
      default-destination: taco.order.queue