spring:
  application:
    name: taco-config-server
  profiles:
    active:
      - git
      - vault
  cloud:
    config:
      server:
        git:
          uri: https://github.com/andreybevilacqua/taco-cloud-config.git
          search-paths: config, another_config
#          username: test
#          password: test
          skip-ssl-validation: true
        vault:
          host: http://127.0.0.1:8200
          port: 8200
          scheme: http
          order: 1

server:
  port: 8888