spring:
  application:
    name: taco-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/andreybevilacqua/taco-cloud-config.git
          search-paths: config, another_config
#          username: test
#          password: test
          skip-ssl-validation: true

server:
  port: 8888