server:
  port: 8090

spring:
  application:
    name: Taco-Reactive-API
  cloud:
    config:
      uri: http://localhost:8888
  data:
    mongodb:
      host: localhost
      port: 27018
      database: taco-reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka