spring:
  application:
    name: Taco-Client
  cloud:
    config:
      uri: http://localhost:8888
server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka